import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { Toaster } from "~/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const healTheWebA = localFont({
  src: "../public/fonts/HealTheWebA-Regular.otf",
  variable: "--font-heal-the-web-a",
  display: "swap",
});

const healTheWebB = localFont({
  src: "../public/fonts/HealTheWebB-Regular.otf",
  variable: "--font-heal-the-web-b",
  display: "swap",
});

export const metadata: Metadata = {
  title: "matt-init",
  description: "Generated by matt-init",
  icons: {
    icon: "https://fav.farm/🕷️",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${healTheWebA.variable}
          ${healTheWebB.variable}
          antialiased
        `}
      >
        {children}
        <Toaster
          position="top-center"
        />
      </body>
    </html>
  );
}
